import { vi } from 'vitest'

const mockCtx = {
  canvas: {} as HTMLCanvasElement,
  clearRect: vi.fn(),
  fillRect: vi.fn(),
  fillText: vi.fn(),
  strokeText: vi.fn(),
  measureText: vi.fn(() => ({ width: 10, actualBoundingBoxAscent: 0, actualBoundingBoxDescent: 0 })),
  beginPath: vi.fn(),
  closePath: vi.fn(),
  moveTo: vi.fn(),
  lineTo: vi.fn(),
  arc: vi.fn(),
  ellipse: vi.fn(),
  quadraticCurveTo: vi.fn(),
  bezierCurveTo: vi.fn(),
  rect: vi.fn(),
  fill: vi.fn(),
  stroke: vi.fn(),
  save: vi.fn(),
  restore: vi.fn(),
  translate: vi.fn(),
  rotate: vi.fn(),
  scale: vi.fn(),
  setLineDash: vi.fn(),
  createLinearGradient: vi.fn(() => ({ addColorStop: vi.fn() })),
  createRadialGradient: vi.fn(() => ({ addColorStop: vi.fn() })),
  drawImage: vi.fn(),
  getImageData: vi.fn(() => ({ data: new Uint8ClampedArray(4), width: 1, height: 1 })),
  putImageData: vi.fn(),
  globalAlpha: 1,
  fillStyle: '',
  strokeStyle: '',
  lineWidth: 1,
  lineCap: 'butt',
  lineJoin: 'miter',
  font: '10px sans-serif',
  textAlign: 'left',
  textBaseline: 'alphabetic',
  shadowBlur: 0,
  shadowColor: '',
  shadowOffsetX: 0,
  shadowOffsetY: 0,
  filter: 'none',
  globalCompositeOperation: 'source-over',
  miterLimit: 10,
  direction: 'ltr',
  roundRect: vi.fn(),
  createPattern: vi.fn(() => null as never),
  createImageData: vi.fn(() => ({ data: new Uint8ClampedArray(4), width: 1, height: 1 })),
  isPointInPath: vi.fn(() => false),
  isPointInStroke: vi.fn(() => false),
  clip: vi.fn(),
  arcTo: vi.fn(),
  getLineDash: vi.fn(() => []),
  transform: vi.fn(),
  setTransform: vi.fn(),
  resetTransform: vi.fn(),
} as unknown as CanvasRenderingContext2D

HTMLCanvasElement.prototype.getContext = vi.fn(() => mockCtx) as any
HTMLCanvasElement.prototype.getBoundingClientRect = vi.fn(() => ({
  x: 0, y: 0, width: 800, height: 600,
  top: 0, right: 800, bottom: 600, left: 0,
  toJSON: () => ({}),
}))

const store = new Map<string, string>()
vi.stubGlobal('localStorage', {
  getItem: vi.fn((key: string) => store.get(key) ?? null),
  setItem: vi.fn((key: string, val: string) => store.set(key, val)),
  removeItem: vi.fn((key: string) => store.delete(key)),
  clear: vi.fn(() => store.clear()),
  length: 0,
  key: vi.fn(() => null),
})
